using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DPS_Diablo3
{
    public class Class_lang
    {
        public string lb_dmg_at, lb_perc_at, lb_speed_at, tb_dmg1_pt, tb_ac1_pt, tb_dmg2_pt, tb_ac2_pt, lb_toskill_at, lb_elem_at, lb_skill_at, lb_skill_usage_at,
        lb_wept, lb_dam_wt, lb_main_wt, lb_damp_wt, lb_acp_wt, lb_cd_wt, lb_elem_wt, lb_wdt, lb_gargt, lb_dogst, lb_fett, lb_fizpt, lb_dampt, lb_sppt,
        lb_statct, lb_acct, lb_mainct, lb_damct, lb_ccct, lb_cdct, lb_elemct, lb_help1t, lb_help2t, lb_help3t, lb_help4t, lb_help5t, lb_help6t, lb_help7t,
        lb_help8t, lb_idmg1t, lb_iac1t, tb_damage2t, lb_icct, lb_icdt, lb_imaint, lb_iasit, lb_iofft, lb_iamut, lb_ir1t, lb_ir2t, lb_ifromskillst, lb_ielitet,
        lb_itoskillt, lb_ielemt, lb_iskillt, lb_dpspt, lb_dpst, lb_dpsrt, lb_dpspetst, lb_result_profilet, lb_resultt, lb_changedt,
        lb_result_wdt, b_advt, b_statt, b_wept, cb_wdt, b_startt, b_savet, b_loadt, b_cleart, lb_autht, Save_dialog1t, Save_dialog2t, Save_dialog3t,
        tt1t, tt2t, tt3t, tt4t, tt5t, tt6t, tt7t, tt8t, tt9t, tt10t, tt11t, tt12t, tt13t, tt14t, tt15t, tt16t, tt17t, tt7_1t, tt18t, tt19t,
        tt20t, tt21t, tt22t, tt23t, tt24t, tt25t, tt26t, tt27t, tt28t, tt29t, tt30t, tt31t, tt32t, tt33t, tt34t, tt35t, tt36t, tt37t, tt38t, tt39t, tt40t, tt41t
        ,lb_resultt_none, lb_resultt_dots, b_advt_def, b_statt_cdr, b_statt_dps, b_wept_wd, b_wept_skill
        ,lb_as_dpst, lb_stat_dpst, lb_cc_dpst, lb_cd_dpst, lb_elem_dpst, lb_dmg_dpst
        ;

        public void Lang_rus()
        {
            lb_dmg_at = "Урон оружия";
            lb_perc_at = "+% урона оружия";
            lb_speed_at = "+% скорости оружия";
            lb_toskill_at = "+% к скиллу";
            lb_elem_at = "+% элементального урона";
            lb_skill_at = "% урона от оружия скилла";
            lb_skill_usage_at = "% использования скилла";
            lb_wept = "Расчёт изменения оружия:";
            lb_dam_wt = "+- Урон оружия";
            lb_main_wt = "+- Основной параметр";
            lb_damp_wt = "+-% урона оружия";
            lb_acp_wt = "+-% скорости оружия";
            lb_cd_wt = "+- Критурон";
            lb_elem_wt = "+- Элементальный урон";
            lb_wdt = "Расчёт урона от питомцев (WD):";
            lb_gargt = "% урона Громадня";
            lb_dogst = "Кол-во собак (если есть)";
            lb_fett = "Среднее кол-во фетишей";
            lb_fizpt = "+% физ. урона для петов";
            lb_dampt = "+% к урону петов";
            lb_sppt = "+% к скорости петов";
            lb_statct = "Изменение статов - изменение DPS:";
            lb_acct = "+- Скорость атаки";
            lb_mainct = "+- Основной параметр";
            lb_damct = "+-  Средний урон (min+max)/2";
            lb_ccct = "+- Критшанс";
            lb_cdct = "+- Критурон";
            lb_elemct = "+- Элементальный урон";
            lb_help1t = "Введите основные параметры и";
            lb_help2t = "используйте кнопку Расчёт DPS.";
            lb_help3t = "Кнопки Save/Load/Clear служат для";
            lb_help4t = "сохранения/загрузки/очистки";
            lb_help5t = "экранных данных.";
            lb_help6t = "Блок справа служит для подсчёта";
            lb_help7t = "изменений при смене вещей.";
            lb_help8t = "Weapon 2 - для данных по оружию 2.";
            lb_idmg1t = "Урон/сек оружие";
            lb_iac1t = "Скорость оружия";
            lb_icct = "Критшанс";
            lb_icdt = "Критурон";
            lb_imaint = "Основной параметр";
            lb_iasit = "+%скорости (эквип)";
            lb_iofft = "Урон от оффхенда";
            lb_iamut = "Урон от амулета";
            lb_ir1t = "Урон от кольца 1";
            lb_ir2t = "Урон от кольца 2";
            lb_ifromskillst = "+% урона от скиллов";
            lb_ielitet = "+% к урону по элите";
            lb_itoskillt = "+% к скиллу";
            lb_ielemt = "+% элементального урона";
            lb_iskillt = "% урона от оружия скилла";
            lb_dpspt = "DPS - профиль:";
            lb_dpst = "DPS: ";
            lb_dpsrt = "DPS - реролл: ";
            lb_dpspetst = " +Pets DPS:";
            lb_result_profilet = "(приблизительно)";
            lb_resultt = "Результаты";
            lb_resultt_none = "Не введены значения";
            lb_resultt_dots = "Проблемы с точками";
            lb_changedt = "Урон после изменений";
            lb_result_wdt = "+ урон петов";
            b_advt = "Высокая\r\nточность";
            b_advt_def = "Обычная\r\nточность";
            b_statt = "Прирост DPS / Skill cooldown";
            b_statt_cdr = "Учёт умения с кулдауном";
            b_statt_dps = "Прирост DPS от характеристик";
            b_wept = "Расчёт изменения оружия";
            b_wept_wd = "Расчёт урона питомцев WD";
            b_wept_skill = "Расчёт изменения параметров";
            cb_wdt = "WD";
            b_startt = "Расчёт DPS";
            b_savet = "Q.Save";
            b_loadt = "Q.Load";
            b_cleart = "Clear";
            lb_autht = "Автор: Dmitry Olenin";
            Save_dialog1t = "Внимание";
            Save_dialog2t = "Хотите сохранить? ";
            Save_dialog3t = "Предыдущие данные будут перезаписаны!";
            lb_as_dpst = "+ 1% AC увеличит DPS:";
            lb_stat_dpst = "+ 100 Stat увеличит DPS:";
            lb_cc_dpst = "+ 1% КШ увеличит DPS:";
            lb_cd_dpst = "+ 10% КУ увеличит DPS:";
            lb_elem_dpst = "+ 1% Elem увеличит DPS:";
            lb_dmg_dpst = "+ 50 Dmg увеличит DPS:";

            tt1t = "Сохраняет данные, прошлые будут перезаписаны.";
            tt2t = "Загружает сохранённые данные.";
            tt3t = "Очищает поля ввода. ---F7---";
            tt4t = "DPS, написанный на оружии в профиле.";
            tt5t = "Скорость оружия, на оружии в профиле.";
            tt6t = "Основной параметр персонажа.";
            tt7t = "Сумма увеличения скорости атаки с вещей (кроме оружия). ";
            tt7_1t = "+15% скорости, если два оружия, не забываем.";
            tt8t = "Критшанс, в профиле персонажа.";
            tt9t = "Критурон, в профиле персонажа.";
            tt10t = "Средний урон на сфере/обереге/колчане.";
            tt11t = "Средний урон на амулете.";
            tt12t = "Средний урон на кольце слева.";
            tt13t = "Средний урон на кольце справа.";
            tt14t = "Общее увеличение урона от пассивок, активных скиллов.";
            tt15t = "Увеличение элементального урона стихии скилла, который считаем.";
            tt16t = "Увеличение урона скилла (+% урона скилла такого-то).";
            tt17t = "Увеличение урона по элите.";
            tt18t = "Процент урона скилла, написан на самом скилле.";
            tt19t = "Минимум и максимум урона оружия (второе опционально).";
            tt20t = "+% урона на оружии, если есть (второе опционально).";
            tt21t = "Процент урона скилла, написан на самом скилле (второе опционально).";
            tt22t = "Процент времени пользования 1 и 2 скиллом (примерно).";
            tt23t = "Увеличение скорости на оружии, если есть (второе опционально).";
            tt24t = "Увеличение урона скиллов (+% урона скилла такого-то).";
            tt25t = "Увеличение элементального урона стихии скиллов.";
            tt26t = "Увеличение урона оружия (разница между новыми и старыми показателями).";
            tt27t = "Новые показатели основного параметра на оружии.";
            tt28t = "Изменение % урона на оружии.";
            tt29t = "Изменение % скорости на оружии.";
            tt30t = "Изменение критического урона на оружии.";
            tt31t = "Изменение элементального урона на оружии.";
            tt32t = "Ссылка на форум с описанием.";
            tt33t = "Время отката скилла в секундах.";
            tt34t = "Сокращение времени отката с источников 1/2.";
            tt35t = "Сокращение времени отката с источников 3/4.";
            tt36t = "Сокращение времени отката с источников 5/6.";
            tt37t = "Сокращение времени отката с источников 7/8.";
            tt38t = "Сокращение времени отката с источников 7/8.";
            tt39t = "Быстрое сохранение данных. ---F5---";
            tt40t = "Быстрая загрузка данных. ---F6---";
            tt41t = "Импорт данных из профиля Battle.Net";
        }

        public void Lang_eng()
        {
            lb_dmg_at = "Weapon Damage";
            lb_perc_at = "+% Weapon Damage";
            lb_speed_at = "+% Attack speed";
            tb_dmg1_pt = "Weapon 1";
            tb_ac1_pt = "Weapon 1";
            tb_dmg2_pt = "Weapon 2";
            tb_ac2_pt = "Weapon 2";
            lb_toskill_at = "+% Skill increase";
            lb_elem_at = "+% Elemental Damage";
            lb_skill_at = "% Weapon Skill Damage";
            lb_skill_usage_at = "% Skill usage";
            lb_wept = "Weapon Stats Adjustment:";
            lb_dam_wt = "+- Weapon Damage";
            lb_main_wt = "+- Main Stat";
            lb_damp_wt = "+-% Weapon Damage";
            lb_acp_wt = "+-% Weapon Attack Speed";
            lb_cd_wt = "+- Critical Hit Damage";
            lb_elem_wt = "+- Elemental Damage";
            lb_wdt = "Pets Damage (WD):";
            lb_gargt = "% Gargantuan Damage";
            lb_dogst = "Zombie dogs number";
            lb_fett = "Fetishes number";
            lb_fizpt = "+% Physical damage";
            lb_dampt = "+% Pets Damage";
            lb_sppt = "+% Pets Attack Speed";
            lb_statct = "Primary Stats Adjustment:";
            lb_acct = "+- Attack Speed";
            lb_mainct = "+- Main Stat";
            lb_damct = "+- Average Damage (min-max)/2";
            lb_ccct = "+- Critical Hit Chance";
            lb_cdct = "+- Critical Hit Damage";
            lb_elemct = "+- Elemental Damage";
            lb_help1t = "Fill Required Fields";
            lb_help2t = "to calculate DPS.";
            lb_help3t = "Use Save/Load/Clear buttons ";
            lb_help4t = "for saving/loading/clearing ";
            lb_help5t = "data.";
            lb_help6t = "Right block is using for calculate";
            lb_help7t = "items/stats changes.";
            lb_help8t = "Weapon 2 - for Dual Wield";
            lb_idmg1t = "Weapon Damage";
            lb_iac1t = "Attacks per Second";
            tb_damage2t = "Weapon 2";
            lb_icct = "Critical Hit Chance";
            lb_icdt = "Critical Hit Damage";
            lb_imaint = "Main Stat";
            lb_iasit = "+% Attack Speed (equip)";
            lb_iofft = "Offhand (min-max)";
            lb_iamut = "Amulet (min-max)";
            lb_ir1t = "Ring 1 (min-max)";
            lb_ir2t = "Ring 2 (min-max)";
            lb_ifromskillst = "+% Skill damage";
            lb_ielitet = "+% Elite damage";
            lb_itoskillt = "+% Skill increase";
            lb_ielemt = "+% Elemental Damage";
            lb_iskillt = "% Weapon Skill Damage";
            lb_dpspt = "Profile DPS:";
            lb_dpst = "Effective DPS:";
            lb_dpsrt = "DPS - reroll:";
            lb_dpspetst = " +Pets DPS:";
            lb_result_profilet = "(approximate)";
            lb_resultt = "Results";
            lb_resultt_none = "Enter values";
            lb_resultt_dots = "Problems with dots";
            lb_changedt = "Damage after changes";
            lb_result_wdt = "+pets dps";
            b_advt = "Detailed";
            b_advt_def = "Simple";
            b_statt = "Increasing DPS / Skill cooldown";
            b_statt_cdr = "Cooldown for skill";
            b_statt_dps = "DPS increase from stats";
            b_wept = "Weapon changes calculator";
            b_wept_wd = "Pets damage calculator (WD)";
            b_wept_skill = "Items/stats calculator";
            cb_wdt = "WD";
            b_startt = "Calculate DPS";
            b_savet = "Q.Save";
            b_loadt = "Q.Load";
            b_cleart = "Clear";
            lb_autht = "Author: Dmitry Olenin";
            Save_dialog1t = "Attention!";
            Save_dialog2t = "Do you want to save data?";
            Save_dialog3t = "Previous data will be overwritten!";
            lb_as_dpst = "+1% AS increase DPS:";
            lb_stat_dpst = "+100 Stat increase DPS:";
            lb_cc_dpst = "+1% CC increase DPS:";
            lb_cd_dpst = "+10% CD increase DPS:";
            lb_elem_dpst = "+1% Elem. increase DPS:";
            lb_dmg_dpst = "+50 Av. Dmg increase DPS:";

            tt1t = "Save data. Previous data will be overwritten!";
            tt2t = "Load data.";
            tt3t = "Reset all data. ---F7---";
            tt4t = "DPS in profile.";
            tt5t = "Weapon Attack Speed in profile.";
            tt6t = "Main Stat.";
            tt7t = "+% Attack Speed from equip";
            tt7_1t = "Don't forget add +15% Attack Speed if dual wield.";
            tt8t = "Critical Hit Chance in profile.";
            tt9t = "Critical Hit Damage in profile.";
            tt10t = "Offhand average damage.";
            tt11t = "Amulet average damage.";
            tt12t = "Left ring average damage.";
            tt13t = "Right ring average damage.";
            tt14t = "Total damage increase from passive and active skills.";
            tt15t = "+% elemental damage for current skill.";
            tt16t = "+ % skill damage.";
            tt17t = "+ % elite damage.";
            tt18t = "% skill weapon damage(see on skill tooltip).";
            tt19t = "min-max weapon damage.";
            tt20t = "+ % damage on weapon.";
            tt21t = "+ % damage on skill(see on skill tooltip).";
            tt22t = "Percentage of time use 1st and 2nd skill(approx).";
            tt23t = "+ % attack speed on weapon.";
            tt24t = "+ % skills damage.";
            tt25t = "Increase elemental damage for skill.";
            tt26t = "Increased weapon damage (the difference between the new and old rates).";
            tt27t = "New value of main parameter on weapon.";
            tt28t = "Change% damage on the weapon.";
            tt29t = "Change% attack speed on the weapon.";
            tt30t = "Change% crit damage on the weapon.";
            tt31t = "Change% elemental damage on the weapon.";
            tt32t = "Link to homepage.";
            tt33t = "Skill cooldown(sec).";
            tt34t = "Source cooldown reduce 1 / 2.";
            tt35t = "Source cooldown reduce 3 / 4.";
            tt36t = "Source cooldown reduce 5 / 6.";
            tt37t = "Source cooldown reduce 7 / 8.";
            tt38t = "Source cooldown reduce 7 / 8.";
            tt39t = "Quick Save Data. ---F5---";
            tt40t = "Quick Load Data. ---F6---";
            tt41t = "Battle.Net profile import.";
        }
    }
}
