using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DPS_Diablo3
{
    public class Class_lang
    {
        public string lb_dmg_at, lb_perc_at, lb_speed_at, tb_dmg1_pt, tb_ac1_pt, tb_dmg2_pt, tb_ac2_pt, lb_toskill_at, lb_elem_at, lb_skill_at, lb_skill_usage_at,
        lb_wept, lb_dam_wt, lb_main_wt, lb_damp_wt, lb_acp_wt, lb_cd_wt, lb_elem_wt, lb_wdt, lb_gargt, lb_dogst, lb_fett, lb_fizpt, lb_dampt, lb_sppt,
        lb_statct, lb_acct, lb_mainct, lb_damct, lb_ccct, lb_cdct, lb_elemct, lb_help1t, lb_help2t, lb_help3t, lb_help4t, lb_help5t, lb_help6t, lb_help7t,
        lb_help8t, lb_idmg1t, lb_iac1t, tb_damage2t, lb_icct, lb_icdt, lb_imaint, lb_iasit, lb_iofft, lb_iamut, lb_ir1t, lb_ir2t, lb_ifromskillst, lb_ielitet,
        lb_itoskillt, lb_ielemt, lb_iskillt, lb_dpspt, lb_dpst, lb_dpsrt, lb_dpspetst, lb_result_profilet, lb_resultt, lb_changedt, lb_eliteс,
        lb_result_wdt, b_advt, b_statt, b_wept, cb_wdt, b_startt, b_savet, b_loadt, b_cleart, lb_autht, Save_dialog1t, Save_dialog2t, Save_dialog3t,
        tt1t, tt2t, tt3t, tt4t, tt5t, tt6t, tt7t, tt8t, tt9t, tt10t, tt11t, tt12t, tt13t, tt14t, tt15t, tt16t, tt17t, tt7_1t, tt18t, tt19t,
        tt20t, tt21t, tt22t, tt23t, tt24t, tt25t, tt26t, tt27t, tt28t, tt29t, tt30t, tt31t, tt32t, tt33t, tt34t, tt35t, tt36t, tt37t, tt38t, tt39t, tt40t, tt41t
        ,lb_resultt_none, lb_resultt_dots, b_advt_def, b_statt_cdr, b_statt_dps, b_wept_wd, b_wept_skill
        , lb_as_dpst, lb_stat_dpst, lb_cc_dpst, lb_cd_dpst, lb_elem_dpst, lb_dmg_dpst, lb_elite_dpst, tb_pers, lb_changes, lb_import, gb_result, gb_increase
        , warn, mess_imp, mess_nopers, mess_noint
        , qu, an, q1, a1_1, a1_2, q2, a2_1, q3, a3_1, a3_2, q4, a4_1, q5, a5_1, q6, a6_1, q7, a7_1, a7_2, q8, a8_1, a8_2, q9, a9_1, q10, a10_1, q11, a11_1, a11_2, q12, a12_1
        , lb_as, lb_cdr, lb_paragon
        ;

        public void Lang_rus()
        {
            lb_paragon = "Уровень парагона: ";
            lb_as = "Скорость атаки";
            lb_cdr = "Снижение времени";
            warn = "Внимание";
            mess_imp = "Неверная строка импорта";
            mess_nopers = "Персонаж не найден";
            mess_noint = "Проблемы с интернетом";
            gb_result = "Результаты расчётов";
            gb_increase = "Прирост DPS от характеристик:";
            //lb_changes = "Выберите вариант для доп. расчётов";
            lb_changes = "Варианты расчёта изменений";
            lb_import = "Вставьте адрес профиля из браузера:";
            tb_pers = "Строка \"http://\" из Battle.Net";
            lb_dmg_at = "Урон оружия";
            lb_perc_at = "+% урона оружия";
            lb_speed_at = "+% скорости оружия";
            lb_toskill_at = "+% к скиллу";
            lb_elem_at = "+% элементального урона";
            lb_skill_at = "% урона от оружия скилла";
            lb_skill_usage_at = "% использования скилла";
            lb_wept = "Расчёт изменения оружия:";
            lb_dam_wt = "+- Урон оружия";
            lb_main_wt = "+- Основной параметр";
            lb_damp_wt = "+-% урона оружия";
            lb_acp_wt = "+-% скорости оружия";
            lb_cd_wt = "+- Критурон";
            lb_elem_wt = "+- Элементальный урон";
            lb_wdt = "Расчёт урона от питомцев (WD):";
            lb_gargt = "% урона Громадня";
            lb_dogst = "Кол-во собак (если есть)";
            lb_fett = "Среднее кол-во фетишей";
            lb_fizpt = "+% физ. урона для петов";
            lb_dampt = "+% к урону петов";
            lb_sppt = "+% к скорости петов";
            lb_statct = "Изменение статов - изменение DPS:";
            lb_acct = "+- Скорость атаки";
            lb_mainct = "+- Основной параметр";
            lb_damct = "+-  Средний урон"; //(min+max)/2
            lb_ccct = "+- Критшанс";
            lb_cdct = "+- Критурон";
            lb_elemct = "+- Элементальный урон";
            lb_help1t = "Введите основные параметры и";
            lb_help2t = "используйте кнопку Расчёт DPS.";
            lb_help3t = "Пункты Save/Load/Clear служат для";
            lb_help4t = "сохранения/загрузки/очистки";
            lb_help5t = "экранных данных.";
            lb_help6t = "Блок справа служит для подсчёта";
            lb_help7t = "изменений при смене вещей.";
            lb_help8t = "weapon2 - для данных по оружию 2.";
            lb_idmg1t = "Урон/сек оружие";
            lb_iac1t = "Скорость оружия";
            lb_icct = "Критшанс";
            lb_icdt = "Критурон";
            lb_imaint = "Основной параметр";
            lb_iasit = "+%скорости (эквип)";
            lb_iofft = "Урон от оффхенда";
            lb_iamut = "Урон от амулета";
            lb_ir1t = "Урон от кольца 1";
            lb_ir2t = "Урон от кольца 2";
            lb_ifromskillst = "+% урона от скиллов";
            lb_ielitet = "+% к урону по элите";
            lb_itoskillt = "+% к скиллу";
            lb_ielemt = "+% элементального урона";
            lb_iskillt = "% урона от оружия скилла";
            lb_dpspt = "DPS - профиль:";
            lb_dpst = "DPS: ";
            lb_dpsrt = "DPS - реролл: ";
            lb_dpspetst = " +Pets DPS:";
            lb_result_profilet = "(приблизительно)";
            lb_resultt = "Результаты";
            lb_resultt_none = "Не введены значения";
            lb_resultt_dots = "Проблемы с точками";
            lb_changedt = "Урон после изменений";
            lb_result_wdt = "+ урон петов";
            b_advt = "Высокая\r\nточность";
            b_advt_def = "Обычная\r\nточность";
            b_statt = "Прирост DPS / Skill cooldown";
            b_statt_cdr = "Учёт умения с кулдауном";
            b_statt_dps = "Прирост DPS от характеристик";
            b_wept = "Расчёт изменения оружия";
            b_wept_wd = "Расчёт урона питомцев WD";
            b_wept_skill = "Расчёт изменения параметров";
            cb_wdt = "WD";
            b_startt = "Расчёт DPS";
            b_savet = "Q.Save";
            b_loadt = "Q.Load";
            b_cleart = "Clear";
            lb_autht = "Автор: Dmitry Olenin";
            Save_dialog1t = "Внимание";
            Save_dialog2t = "Хотите сохранить? ";
            Save_dialog3t = "Предыдущие данные будут перезаписаны!";
            lb_as_dpst = "+ 1% AC увеличит DPS:";
            lb_stat_dpst = "+ 100 Stat увеличит DPS:";
            lb_cc_dpst = "+ 1% КШ увеличит DPS:";
            lb_cd_dpst = "+ 10% КУ увеличит DPS:";
            lb_elem_dpst = "+ 1% Elem увеличит DPS:";
            lb_dmg_dpst = "+ 10 Dmg увеличит DPS:";
            lb_elite_dpst = "+ 1% Elite увеличит DPS:";
            lb_eliteс = "+-% Урона по элите";

            tt1t = "Сохраняет данные, прошлые будут перезаписаны.";
            tt2t = "Загружает сохранённые данные.";
            tt3t = "Очищает поля ввода. ---F7---";
            tt4t = "DPS, написанный на оружии в профиле.";
            tt5t = "Скорость оружия, на оружии в профиле.";
            tt6t = "Основной параметр персонажа.";
            tt7t = "Сумма увеличения скорости атаки с вещей (кроме оружия). ";
            tt7_1t = "+15% скорости, если два оружия, не забываем.";
            tt8t = "Критшанс, в профиле персонажа.";
            tt9t = "Критурон, в профиле персонажа.";
            tt10t = "Средний урон на сфере/обереге/колчане.";
            tt11t = "Средний урон на амулете.";
            tt12t = "Средний урон на кольце слева.";
            tt13t = "Средний урон на кольце справа.";
            tt14t = "Общее увеличение урона от пассивок, активных скиллов.";
            tt15t = "Увеличение элементального урона стихии скилла, который считаем.";
            tt16t = "Увеличение урона скилла (+% урона скилла такого-то).";
            tt17t = "Увеличение урона по элите.";
            tt18t = "Процент урона скилла, написан на самом скилле.";
            tt19t = "Минимум и максимум урона оружия (второе опционально).";
            tt20t = "+% урона на оружии, если есть (второе опционально).";
            tt21t = "Процент урона скилла, написан на самом скилле (второе опционально).";
            tt22t = "Процент времени пользования 1 и 2 скиллом (примерно).";
            tt23t = "Увеличение скорости на оружии, если есть (второе опционально).";
            tt24t = "Увеличение урона скиллов (+% урона скилла такого-то).";
            tt25t = "Увеличение элементального урона стихии скиллов.";
            tt26t = "Увеличение урона оружия (разница между новыми и старыми показателями).";
            tt27t = "Новые показатели основного параметра на оружии.";
            tt28t = "Изменение % урона на оружии.";
            tt29t = "Изменение % скорости на оружии.";
            tt30t = "Изменение критического урона на оружии.";
            tt31t = "Изменение элементального урона на оружии.";
            tt32t = "Ссылка на форум с описанием.";
            tt33t = "Время отката скилла в секундах.";
            tt34t = "Сокращение времени отката с источников 1/2.";
            tt35t = "Сокращение времени отката с источников 3/4.";
            tt36t = "Сокращение времени отката с источников 5/6.";
            tt37t = "Сокращение времени отката с источников 7/8.";
            tt38t = "Сокращение времени отката с источников 9/10.";
            tt39t = "Быстрое сохранение данных. ---F5---";
            tt40t = "Быстрая загрузка данных. ---F6---";
            tt41t = "Импорт данных из профиля Battle.Net";

            qu = "Вопрос: ";
            an = "Ответ: ";
            q1 = "Для чего эта программа нужна?";
            a1_1 = "Программа нужна для вычисления урона 1 или 2 скиллов, которыми пользуется персонаж.";
            a1_2 = "Также она может быть полезна при изменении экипировки или вложении очков парагона.";
            q2 = "Опасно ли пользоваться данной программой, не могут ли за это забанить?";
            a2_1 = "Нет, не опасно, забанить не могут, программа никак не взаимодействует с игрой.";
            q3 = "Я боюсь вирусов, кражи личной информации и призраков. Как мне быть?";
            a3_1 = "Программа не содержит ничего, что могло бы повредить компьютеру. Проверить можно на сайте virustotal.";
            a3_2 = "Также есть исходные коды на сайте: github.com/DmitryOlenin/DPS_Diablo3.";
            q4 = "Программа не запускается, что делать?";
            a4_1 = "Вам следует установить .Net Framework 4.0 с сайта Microsoft.";
            q5 = "Что отражает значение DPS - профиль?";
            a5_1 = "Это тот DPS, который вам показывает игра. Обычно совпадает, если данные введены правильно.";
            q6 = "Почему профильный DPS так сильно отличается от реального?";
            a6_1 = "Профильный DPS не учитывает многих факторов, таких как элементальный урон, прибавка урона скилла.";
            q7 = "Почему при импорте данные могут не совпасть как с профилем в игре, так и с профилем на сайте?";
            a7_1 = "На сайте содержится неверная информация о части оффхендов, неверно считается % урона ";
            a7_2 = "оружия с элементальным уроном, не учитываются прибавки от сетовых вещей, нет информации о парагоне.";
            q8 = "Почему при вводе \"% урона от скилла\" не меняется профильный урон в программе?";
            a8_1 = "Большая часть скиллов в игре не учитывается при расчёте профильного урона, однако есть исключения.";
            a8_2 = "В расчёте реального урона всё учитывается как надо.";
            q9 = "Чем отличается \"Обычная точность\" и \"Высокая точность\"?";
            a9_1 = "В обычном режиме нужно вводить меньше параметров и может быть небольшая погрешность в измерениях.";
            q10 = "Что делает расчёт урона питомцев WD в доп. расчётах?";
            a10_1 = "Считает урон от ваших питомцев, добавляя его к основному урону.";
            q11 = "Как посчитать урон спелла со временем отката?";
            a11_1 = "В доп. расчётах есть пункт, позволяющий выбрать режим обсчёта кулдауна.";
            a11_2 = "Вводите время отката и снижение этого времени с вещей.";
            q12 = "Как посчитать урон скилла, который используется время от времени и не зависит от скорости атаки?";
            a12_1 = "В разделе для ввода кулдауна поставить 1 в пункт \"Skill 1 cooldown\".";
        }

        public void Lang_eng()
        {
            lb_paragon = "Paragon level: ";
            lb_as = "Attack speed";
            lb_cdr = "Cooldown reduce";
            warn = "Warning";
            mess_imp = "Wrong input string";
            mess_nopers = "Profile not found";
            mess_noint = "Problems with internet";
            gb_result = "The results of calculations";
            gb_increase = "Increasing DPS from stats:";
            //lb_changes = "Choose option for advanced calculation";
            lb_changes = "Options of advanced calculation";
            lb_import = "Insert the profile address from the browser:";
            tb_pers = "String \"http://\" from armory";
            lb_dmg_at = "Weapon Damage";
            lb_perc_at = "+% Weapon Damage";
            lb_speed_at = "+% Attack speed";
            tb_dmg1_pt = "weapon1";
            tb_ac1_pt = "weapon1";
            tb_dmg2_pt = "weapon2";
            tb_ac2_pt = "weapon2";
            lb_toskill_at = "+% Skill increase";
            lb_elem_at = "+% Elemental Damage";
            lb_skill_at = "% Weapon Skill Damage";
            lb_skill_usage_at = "% Skill usage";
            lb_wept = "Weapon Stats Adjustment:";
            lb_dam_wt = "+- Weapon Damage";
            lb_main_wt = "+- Main Stat";
            lb_damp_wt = "+-% Weapon Damage";
            lb_acp_wt = "+-% Weapon Attack Speed";
            lb_cd_wt = "+- Critical Hit Damage";
            lb_elem_wt = "+- Elemental Damage";
            lb_wdt = "Pets Damage (WD):";
            lb_gargt = "% Gargantuan Damage";
            lb_dogst = "Zombie dogs number";
            lb_fett = "Fetishes number";
            lb_fizpt = "+% Physical damage";
            lb_dampt = "+% Pets Damage";
            lb_sppt = "+% Pets Attack Speed";
            lb_statct = "Primary Stats Adjustment:";
            lb_acct = "+- Attack Speed";
            lb_mainct = "+- Main Stat";
            lb_damct = "+- Average Damage"; // (min-max)/2
            lb_ccct = "+- Critical Hit Chance";
            lb_cdct = "+- Critical Hit Damage";
            lb_elemct = "+- Elemental Damage";
            lb_help1t = "Fill Required Fields";
            lb_help2t = "to calculate DPS.";
            lb_help3t = "Use Save/Load/Clear from menu";
            lb_help4t = "for saving/loading/clearing ";
            lb_help5t = "data.";
            lb_help6t = "Right block is using for calculate";
            lb_help7t = "items/stats changes.";
            lb_help8t = "weapon2 - for Dual Wield";
            lb_idmg1t = "Weapon Damage";
            lb_iac1t = "Attacks per Second";
            tb_damage2t = "weapon2";
            lb_icct = "Critical Hit Chance";
            lb_icdt = "Critical Hit Damage";
            lb_imaint = "Main Stat";
            lb_iasit = "+% Attack Speed (equip)";
            lb_iofft = "Offhand (min-max)";
            lb_iamut = "Amulet (min-max)";
            lb_ir1t = "Ring 1 (min-max)";
            lb_ir2t = "Ring 2 (min-max)";
            lb_ifromskillst = "+% Skill damage";
            lb_ielitet = "+% Elite damage";
            lb_itoskillt = "+% Skill increase";
            lb_ielemt = "+% Elemental Damage";
            lb_iskillt = "% Weapon Skill Damage";
            lb_dpspt = "Profile DPS:";
            lb_dpst = "Effective DPS:";
            lb_dpsrt = "DPS - reroll:";
            lb_dpspetst = " +Pets DPS:";
            lb_result_profilet = "(approximate)";
            lb_resultt = "Results";
            lb_resultt_none = "Enter values";
            lb_resultt_dots = "Problems with dots";
            lb_changedt = "Damage after changes";
            lb_result_wdt = "+pets dps";
            b_advt = "Detailed";
            b_advt_def = "Simple";
            b_statt = "Increasing DPS / Skill cooldown";
            b_statt_cdr = "Cooldown for skill";
            b_statt_dps = "DPS increase from stats";
            b_wept = "Weapon changes calculator";
            b_wept_wd = "Pets damage calculator (WD)";
            b_wept_skill = "Items/stats calculator";
            cb_wdt = "WD";
            b_startt = "Calculate DPS";
            b_savet = "Q.Save";
            b_loadt = "Q.Load";
            b_cleart = "Clear";
            lb_autht = "Author: Dmitry Olenin";
            Save_dialog1t = "Attention!";
            Save_dialog2t = "Do you want to save data?";
            Save_dialog3t = "Previous data will be overwritten!";
            lb_as_dpst = "+1% AS increase DPS:";
            lb_stat_dpst = "+100 Stat increase DPS:";
            lb_cc_dpst = "+1% CC increase DPS:";
            lb_cd_dpst = "+10% CD increase DPS:";
            lb_elem_dpst = "+1% Elem. increase DPS:";
            lb_dmg_dpst = "+10 Av. Dmg increase DPS:";
            lb_elite_dpst = "+1% Elite increase DPS:";
            lb_eliteс = "+-% Elite damage";

            tt1t = "Save data. Previous data will be overwritten!";
            tt2t = "Load data.";
            tt3t = "Reset all data. ---F7---";
            tt4t = "DPS in profile.";
            tt5t = "Weapon Attack Speed in profile.";
            tt6t = "Main Stat.";
            tt7t = "+% Attack Speed from equip";
            tt7_1t = "Don't forget add +15% Attack Speed if dual wield.";
            tt8t = "Critical Hit Chance in profile.";
            tt9t = "Critical Hit Damage in profile.";
            tt10t = "Offhand average damage.";
            tt11t = "Amulet average damage.";
            tt12t = "Left ring average damage.";
            tt13t = "Right ring average damage.";
            tt14t = "Total damage increase from passive and active skills.";
            tt15t = "+% elemental damage for current skill.";
            tt16t = "+ % skill damage.";
            tt17t = "+ % elite damage.";
            tt18t = "% skill weapon damage(see on skill tooltip).";
            tt19t = "min-max weapon damage.";
            tt20t = "+ % damage on weapon.";
            tt21t = "+ % damage on skill(see on skill tooltip).";
            tt22t = "Percentage of time use 1st and 2nd skill(approx).";
            tt23t = "+ % attack speed on weapon.";
            tt24t = "+ % skills damage.";
            tt25t = "Increase elemental damage for skill.";
            tt26t = "Increased weapon damage (the difference between the new and old rates).";
            tt27t = "New value of main parameter on weapon.";
            tt28t = "Change% damage on the weapon.";
            tt29t = "Change% attack speed on the weapon.";
            tt30t = "Change% crit damage on the weapon.";
            tt31t = "Change% elemental damage on the weapon.";
            tt32t = "Link to forum.";
            tt33t = "Skill cooldown(sec).";
            tt34t = "Source cooldown reduce 1 / 2.";
            tt35t = "Source cooldown reduce 3 / 4.";
            tt36t = "Source cooldown reduce 5 / 6.";
            tt37t = "Source cooldown reduce 7 / 8.";
            tt38t = "Source cooldown reduce 9 / 10.";
            tt39t = "Quick Save Data. ---F5---";
            tt40t = "Quick Load Data. ---F6---";
            tt41t = "Battle.Net profile import.";

            qu = "Question: ";
            an = "Answer: ";
            q1 = "What does this program do?";
            a1_1 = "Program is needed to calculate the damage one or two skills, which uses character.";
            a1_2 = "It can also be useful when changing equipment or adding points of Paragon.";
            q2 = "Is it dangerous to use this program, can i get the ban for using it?";
            a2_1 = "No, not dangerous, you will not get a ban, the program does not interact with the game.";
            q3 = "I'm afraid of viruses, identity thieves and ghosts. What can I do?";
            a3_1 = "The program does not contain anything that could harm your computer. You can check this site virustotal.";
            a3_2 = "Also there is the source code on the website: github.com/DmitryOlenin/DPS_Diablo3.";
            q4 = "The program does not start, what to do?";
            a4_1 = "You should install .Net Framework 4.0 from Microsoft.";
            q5 = "What reflects the value of DPS - Profile?";
            a5_1 = "This is the DPS, which game shows you. Usually identical if the data is entered correctly.";
            q6 = "Why profile DPS is so different from the real DPS?";
            a6_1 = "Profile DPS ignores many factors, such as elemental damage, increase from skill damage.";
            q7 = "Why after importing data, profile in the game not matched with a profile on the site?";
            a7_1 = "The site contains incorrect information about the part offhands, incorrectly calculated % damage";
            a7_2 = "weapons with elemental damage, not accounted set items, there is no information about Paragon.";
            q8 = "Why \"% damage from skill\" does not change profile DPS in the program?";
            a8_1 = "Most of the skills in the game is not considered when calculating the profile DPS, but there are exceptions.";
            a8_2 = "The calculation of the real DPS working as it should.";
            q9 = "What is the difference between Normal mode and Simple mode?";
            a9_1 = "In Simple mode, you will enter fewer parameters and may be a slight error in the measurements.";
            q10 = "What does the \"Pets damage calculator\" in advanced calculation?";
            a10_1 = "Considers the damage done by your pets by adding it to the main damage.";
            q11 = "How to calculate the damage over time spell with rollback?";
            a11_1 = "Advanced calculation service allow you to select mode calculation cooldown.";
            a11_2 = "Enter the cooldown time and cooldown reduction from sources.";
            q12 = "How to calculate DPS of skill that is used from time to time and does not depend on the speed of the attack?";
            a12_1 = "Put 1 in \"Skill 1 cooldown\" in the cooldown part of advanced calculation.";

        }
    }
}
