//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18408
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPS_Diablo3.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Paragon : global::System.Configuration.ApplicationSettingsBase {
        
        private static Paragon defaultInstance = ((Paragon)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Paragon())));
        
        public static Paragon Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal nud_para_main {
            get {
                return ((decimal)(this["nud_para_main"]));
            }
            set {
                this["nud_para_main"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal nud_para_as {
            get {
                return ((decimal)(this["nud_para_as"]));
            }
            set {
                this["nud_para_as"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal nud_para_cdr {
            get {
                return ((decimal)(this["nud_para_cdr"]));
            }
            set {
                this["nud_para_cdr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal nud_para_cc {
            get {
                return ((decimal)(this["nud_para_cc"]));
            }
            set {
                this["nud_para_cc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal nud_para_cd {
            get {
                return ((decimal)(this["nud_para_cd"]));
            }
            set {
                this["nud_para_cd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string lb_para_lvl {
            get {
                return ((string)(this["lb_para_lvl"]));
            }
            set {
                this["lb_para_lvl"] = value;
            }
        }
    }
}
