//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18408
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPS_Diablo3.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string tb_damage1 {
            get {
                return ((string)(this["tb_damage1"]));
            }
            set {
                this["tb_damage1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Оружие 2")]
        public string tb_damage2 {
            get {
                return ((string)(this["tb_damage2"]));
            }
            set {
                this["tb_damage2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string tb_ac1 {
            get {
                return ((string)(this["tb_ac1"]));
            }
            set {
                this["tb_ac1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Оружие 2")]
        public string tb_ac2 {
            get {
                return ((string)(this["tb_ac2"]));
            }
            set {
                this["tb_ac2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string tb_main {
            get {
                return ((string)(this["tb_main"]));
            }
            set {
                this["tb_main"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string tb_acincr {
            get {
                return ((string)(this["tb_acincr"]));
            }
            set {
                this["tb_acincr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string tb_cc {
            get {
                return ((string)(this["tb_cc"]));
            }
            set {
                this["tb_cc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string tb_cd {
            get {
                return ((string)(this["tb_cd"]));
            }
            set {
                this["tb_cd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string tb_off_min {
            get {
                return ((string)(this["tb_off_min"]));
            }
            set {
                this["tb_off_min"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string tb_off_max {
            get {
                return ((string)(this["tb_off_max"]));
            }
            set {
                this["tb_off_max"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string tb_am_min {
            get {
                return ((string)(this["tb_am_min"]));
            }
            set {
                this["tb_am_min"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string tb_am_max {
            get {
                return ((string)(this["tb_am_max"]));
            }
            set {
                this["tb_am_max"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string tb_r1_min {
            get {
                return ((string)(this["tb_r1_min"]));
            }
            set {
                this["tb_r1_min"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string tb_r1_max {
            get {
                return ((string)(this["tb_r1_max"]));
            }
            set {
                this["tb_r1_max"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string tb_r2_min {
            get {
                return ((string)(this["tb_r2_min"]));
            }
            set {
                this["tb_r2_min"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string tb_r2_max {
            get {
                return ((string)(this["tb_r2_max"]));
            }
            set {
                this["tb_r2_max"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string tb_other_min {
            get {
                return ((string)(this["tb_other_min"]));
            }
            set {
                this["tb_other_min"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string tb_other_max {
            get {
                return ((string)(this["tb_other_max"]));
            }
            set {
                this["tb_other_max"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string tb_fromskills {
            get {
                return ((string)(this["tb_fromskills"]));
            }
            set {
                this["tb_fromskills"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string tb_elem {
            get {
                return ((string)(this["tb_elem"]));
            }
            set {
                this["tb_elem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string tb_toskill {
            get {
                return ((string)(this["tb_toskill"]));
            }
            set {
                this["tb_toskill"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string tb_elite {
            get {
                return ((string)(this["tb_elite"]));
            }
            set {
                this["tb_elite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string tb_skill {
            get {
                return ((string)(this["tb_skill"]));
            }
            set {
                this["tb_skill"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal nud_garg {
            get {
                return ((decimal)(this["nud_garg"]));
            }
            set {
                this["nud_garg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal nud_dogs {
            get {
                return ((decimal)(this["nud_dogs"]));
            }
            set {
                this["nud_dogs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal nud_fet {
            get {
                return ((decimal)(this["nud_fet"]));
            }
            set {
                this["nud_fet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal nud_elemp {
            get {
                return ((decimal)(this["nud_elemp"]));
            }
            set {
                this["nud_elemp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal nud_damp {
            get {
                return ((decimal)(this["nud_damp"]));
            }
            set {
                this["nud_damp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal nud_speedp {
            get {
                return ((decimal)(this["nud_speedp"]));
            }
            set {
                this["nud_speedp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string tb_dmg1_1_a {
            get {
                return ((string)(this["tb_dmg1_1_a"]));
            }
            set {
                this["tb_dmg1_1_a"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string tb_dmg1_2_a {
            get {
                return ((string)(this["tb_dmg1_2_a"]));
            }
            set {
                this["tb_dmg1_2_a"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("min2")]
        public string tb_dmg2_1_a {
            get {
                return ((string)(this["tb_dmg2_1_a"]));
            }
            set {
                this["tb_dmg2_1_a"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("max2")]
        public string tb_dmg2_2_a {
            get {
                return ((string)(this["tb_dmg2_2_a"]));
            }
            set {
                this["tb_dmg2_2_a"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Оружие 1")]
        public string tb_dmg1_p {
            get {
                return ((string)(this["tb_dmg1_p"]));
            }
            set {
                this["tb_dmg1_p"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Оружие 2")]
        public string tb_dmg2_p {
            get {
                return ((string)(this["tb_dmg2_p"]));
            }
            set {
                this["tb_dmg2_p"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string tb_skill1 {
            get {
                return ((string)(this["tb_skill1"]));
            }
            set {
                this["tb_skill1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("skill2")]
        public string tb_skill2 {
            get {
                return ((string)(this["tb_skill2"]));
            }
            set {
                this["tb_skill2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100%")]
        public string tb_skill1_usage {
            get {
                return ((string)(this["tb_skill1_usage"]));
            }
            set {
                this["tb_skill1_usage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("skill2")]
        public string tb_skill2_usage {
            get {
                return ((string)(this["tb_skill2_usage"]));
            }
            set {
                this["tb_skill2_usage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string tb_elem1 {
            get {
                return ((string)(this["tb_elem1"]));
            }
            set {
                this["tb_elem1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("skill2")]
        public string tb_elem2 {
            get {
                return ((string)(this["tb_elem2"]));
            }
            set {
                this["tb_elem2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string tb_toskill1 {
            get {
                return ((string)(this["tb_toskill1"]));
            }
            set {
                this["tb_toskill1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("skill2")]
        public string tb_toskill2 {
            get {
                return ((string)(this["tb_toskill2"]));
            }
            set {
                this["tb_toskill2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Оружие 1")]
        public string tb_ac1_p {
            get {
                return ((string)(this["tb_ac1_p"]));
            }
            set {
                this["tb_ac1_p"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Оружие 2")]
        public string tb_ac2_p {
            get {
                return ((string)(this["tb_ac2_p"]));
            }
            set {
                this["tb_ac2_p"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string tb_dmg1_w {
            get {
                return ((string)(this["tb_dmg1_w"]));
            }
            set {
                this["tb_dmg1_w"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string tb_dmg2_w {
            get {
                return ((string)(this["tb_dmg2_w"]));
            }
            set {
                this["tb_dmg2_w"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal nud_main_w {
            get {
                return ((decimal)(this["nud_main_w"]));
            }
            set {
                this["nud_main_w"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal nud_damp_w {
            get {
                return ((decimal)(this["nud_damp_w"]));
            }
            set {
                this["nud_damp_w"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal nud_acp_w {
            get {
                return ((decimal)(this["nud_acp_w"]));
            }
            set {
                this["nud_acp_w"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal nud_cd_w {
            get {
                return ((decimal)(this["nud_cd_w"]));
            }
            set {
                this["nud_cd_w"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal nud_elem_w {
            get {
                return ((decimal)(this["nud_elem_w"]));
            }
            set {
                this["nud_elem_w"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal nud_cooldown {
            get {
                return ((decimal)(this["nud_cooldown"]));
            }
            set {
                this["nud_cooldown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal nud_cdr1 {
            get {
                return ((decimal)(this["nud_cdr1"]));
            }
            set {
                this["nud_cdr1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal nud_cdr2 {
            get {
                return ((decimal)(this["nud_cdr2"]));
            }
            set {
                this["nud_cdr2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal nud_cdr3 {
            get {
                return ((decimal)(this["nud_cdr3"]));
            }
            set {
                this["nud_cdr3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal nud_cdr4 {
            get {
                return ((decimal)(this["nud_cdr4"]));
            }
            set {
                this["nud_cdr4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal nud_cdr5 {
            get {
                return ((decimal)(this["nud_cdr5"]));
            }
            set {
                this["nud_cdr5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal nud_cdr6 {
            get {
                return ((decimal)(this["nud_cdr6"]));
            }
            set {
                this["nud_cdr6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal nud_cdr7 {
            get {
                return ((decimal)(this["nud_cdr7"]));
            }
            set {
                this["nud_cdr7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal nud_cdr8 {
            get {
                return ((decimal)(this["nud_cdr8"]));
            }
            set {
                this["nud_cdr8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal nud_cdr9 {
            get {
                return ((decimal)(this["nud_cdr9"]));
            }
            set {
                this["nud_cdr9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal nud_cdr10 {
            get {
                return ((decimal)(this["nud_cdr10"]));
            }
            set {
                this["nud_cdr10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting {
            get {
                return ((string)(this["Setting"]));
            }
            set {
                this["Setting"] = value;
            }
        }
    }
}
